### ISSUE TITLE
Order of the columns isn't preserved

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer#10]
The order of the columns in the table isn't in the original version, e.g., I'm adding data into datastore in the following form - `c,b,a`, however, when it is rendered in the data explorer app, it becomes - `a,b,c`.

This happens because we render data in the order that is returned from the datastore API. Instead of that we could render based on the tableschema if it is provided.

## Acceptance criteria

* [x] I can control order of the columns through tableschema (or data dictionary of datastore)
* [x] The order of the columns are preserved

## Tasks

* [x] Refactor `Table` component of `datapackage-views-js` so that the columns are ordered based on tableschema if available
* [x] Release a new version
* [x] Install in data explorer

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datopian/datapackage-views-js/commit/cb0cd27853efe1209ce6c6981e801972c57555e5

* Available in `datapackage-views-js@1.3.14`
* Will be included in `data-explorer@0.4.8`
