### ISSUE TITLE
Sort filtered results

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer#17]
_When filtering data using, I want to get results sorted in the same order as it is in the database table (or as it is sorted initially) so that I'm not confused by random order of the data rows._

At the moment, there is no sorting and the order of the records are not consistent.

## Acceptance criteria

* [x] The filtered data persists the initial order of the data rows
* [x] The filtered data is ordered in the same way as it is in the db table

## Tasks

* [x] Fix `datastore-query-builder` component:
  * [x] Add `ORDER BY "_id" ASC` option in the query string
  * [x] Test it, compile and release
* [x] Update in Data Explorer so it uses the newly released `datastore-query-builder`
* [x] Release a new version of the Data Explorer

**Comment by anuveyatsu** [comment]
FIXED in v0.4.12
