### ISSUE TITLE
[Data Explorer] Add snaphsots and regression tests

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer#22]
Moved from gitlab, originally created by @starsinmypockets 

As a stakeholder I want to know that the data epxlorer works so that I can count on our toolchain for my business goals

### Acceptance

- [ ] Main componentry is tested
- [ ] CI/CD fails on test failure

### Tasks

- [ ] Bit of research -- below
- [ ] Add tasks after analysis complete

### Analysis [WIP]

**NOTE** Add a bit more analysis on toolchain before starting (cosmos / fixtures / jest / snaphsots / CI)
I think we want to use 

cosmos-test with cosmos fixtures and jest to test application in various states:

Ex:

fixture -> widgets -> active map tab -> map data . :SNAPSHOT:
fixture -> widgets -> chart tab active : :SNAP:

etc

*NOTE* Use shallow compare of HTML
