### ISSUE TITLE
[DOCS] Detailed developer docs for Data-Explorer

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer#23]
# Acceptance criteria

- [ ] Better dev docs on dependency handling / updates to depenencies
- [ ] Document tag structure / semver . compat issues

# Tasks 
 - [ ] We should document some important points regarding data-explorer dependency tree and how to make updates to data-explorer deps:

A real world example:
1. test datapackage-views (manual and automated local testing)
2. test data-explorer (test locally in standalone mode, for instance)
3. integrate and test in ckan-montreal frontend-v2 theme
- [ ] Link to semver docs
- [ ] Discuss backwards compat issues
- [ ] Discuss tagging builds in themes / for consumers

**Comment by anuveyatsu** [comment]
A bit disorganized but further notes from the training session with svetozar

Paul Walker
,
30 mins
,
Edited,
Notes from convo:
* Add test case with datastore API to cosmos fixtures
* QA
* Bundle
* Publish with new minor versions
* Ship

Paul Walker
,
27 mins
,
New
Paul: Document release process

Paul Walker
,
24 mins
,
Edited,
New
1. Merge PR
2. Pull
3. npm publish(publishes to the NPM package repository)
3a. Login (need perms)
3b Increment appropriate version (minor in this case)
4. git tag with "SAME V AS NP PUBLISHED"
5. git push --tags

Paul Walker
,
23 mins
,
Edited,
New

Paul Walker
,
5 mins
,
New
There's a lib called propTypes for react that define required and optional props for components - self documenting and makes collaboration and testing much easier

Paul Walker
,
2 mins
,
New
TODO svetozar:
- [ ] test Table in datapackage view (see my branch)
- [ ] publish data explorer lilbrary
- [ ] push data-explorer tag to github
- [ ] copy to montreal theme and deploy
