### ISSUE TITLE
[Docs] Remove/move README to tech.datopian.com

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer#3]
We need to have single place where all the docs can be found. We've already created http://tech.datopian.com/data-explorer/ page for documenting data-explorer app and now we want to link to that page from the README of this repo.

## Acceptance criteria

* [x] The README links me to http://tech.datopian.com/data-explorer/ 
* [x] The README itself doesn't contain any docs 

## Tasks

* [x] Check the difference between current README and the docs on tech site.
* [x] Add any differences found to tech site.
* [x] Remove docs from README and link to tech site.

**Comment by EvgeniiaVak** [comment]
FIXED. See https://github.com/datopian/data-explorer/pull/14
