### ISSUE TITLE
Integrate this app into CKAN Classic

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer#40]
## Acceptance criteria

* [ ] Make it work with CKAN Classic v2.8 and later
* [ ] Document how it can be setup
* [ ] Mention about this in the docs here - https://docs.ckan.org/en/2.9/maintaining/data-viewer.html?highlight=resource%20view#other-view-plugins

Bonus:

* [ ] This is built-in into CKAN Classic

## Tasks

* [ ] Try out what's missing to make it work with CKAN Classic
* [ ] Check if this works with private datasets, if not  fix it
* [ ] Documentation

...

**Comment by anuveyatsu** [comment]
Most of this is done in https://github.com/datopian/ckanext-dataexplorer-react
