### ISSUE TITLE
Data Explorer fixes re non-datastore resources or views

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer#8]
> When a data pdf file is uploaded it shows a message "total rows".
> See attached for more details.

<img width="734" alt="Screen Shot 2020-03-06 at 16 43 07" src="https://user-images.githubusercontent.com/17809581/76076720-991b7480-5fc9-11ea-913f-460361838be2.png">

> In addition to the comments above, all types of views now have pagination options, total rows and the application of rules - for most types, this is not appropriate (e.g. images and external views) and looks unsuitable

## Acceptance criteria

* [x] No total rows, filters and pagination for PDF previews, non-datastore and non-table resources

## Tasks

* ~~Hide "Total rows" for non-datastore resources~~
  * already working
* [x] Remove "Total rows" for non-datastore views, e.g., `web` and `document` view types
  * see https://github.com/datopian/data-explorer/commit/8cfdbbfdd10fd7ead1d2ad2cbdc4f6ef60b2054f
* [x] Remove pagination and filters for non-datastore resources and non-tables
  * [x] Even if original resource is in datastore and tabular, we still need to check the view type.
    * see https://github.com/datopian/data-explorer/commit/372b29345dc1118fcf1497b61db36739c790fa3e and https://github.com/datopian/data-explorer/commit/2fe20d45e8eddc8f6e872c6dfc7ea81e5eded46a

## Analysis

Reading the client comment + looking at the examples, identified following issues in Data Explorer:

* "Total rows" should be hidden for non-datastore resources as irrelevant.
* Pagination should not be displayed for non-datastore resources and non-tables.
  * Even if original resource is in datastore and tabular, we still need to check the view type.
  * Same applies for filters

**Comment by anuveyatsu** [comment]
FIXED and will be available in next release (>0.4.5).
